In [3]:
import pandas as pd

file = 'C:\\Users\\Bob\Documents\\Repos\\sql-crash-course\\Labs\\Lab 4\\data\\customers_by_total_spent.csv'

In [4]:
customers = pd.read_csv(file)

In [6]:
customers.head()

,first_name,last_name,email,address,address2,city,postal_code,country,customer_is_active,total_revenue_from_customer
0,Aaron,Selby,aaron.selby@sakilacustomer.org,1519 Santiago de los Caballeros Loop,NaN,Mwene-Ditu,22025,"Congo, The Democratic Republic of the",Yes,88.80
1,Adam,Gooch,adam.gooch@sakilacustomer.org,230 Urawa Drive,NaN,Adoni,2738,India,Yes,97.80
2,Adrian,Clary,adrian.clary@sakilacustomer.org,1986 Sivas Place,NaN,Udine,95775,Italy,Yes,68.82
3,Agnes,Bishop,agnes.bishop@sakilacustomer.org,866 Shivapuri Manor,NaN,Sambhal,22474,India,Yes,86.79
4,Alan,Kahn,alan.kahn@sakilacustomer.org,753 Ilorin Avenue,NaN,Emeishan,3656,China,Yes,119.75